pipelines:
  branches:
    dev:
      - step:
          name: Mirror to GitHub main branch
          image: atlassian/default-image:3
          script:
            - git config --global user.email "$BITBUCKET_USER_EMAIL"
            - git config --global user.name "$BITBUCKET_USER_NAME"
            - |
              cat > .gitignore <<EOF
              template-setup.mjs
              bitbucket-pipelines.yml
              EOF
            - git rm --cached template-setup.mjs bitbucket-pipelines.yml
            - git commit -m "Remove template files from git tracking"
            - git remote add github "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/SURGE-GLOBAL-ENGINEERING/reader-scout-custom-template.git"
            - git push github dev:main --force
            - git push github --tags
